### ISSUE TITLE
ValueError: All arrays must be of the same length

### ISSUE THREAD

**Issue by MachineGUN001** [ELELAB/PDBminer#67]
hi, 

thanks for providing so interesting work.

while I try to run the script, `!python PDBminer -i ./examples/input_file/input_file.csv -n 6 -f csv`, input file is the example file in the examaple folder.

the error occurred, as below:

```
Traceback (most recent call last):
  File "c:\CADD\anaconda3\envs\fragbase\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "c:\CADD\anaconda3\envs\fragbase\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "c:\Users\ww\PDBminer-main\PDBminer", line 1635, in process_uniprot
    structural_df = align(combined_structure, uniprot_dir, peptide_min_length)
  File "c:\Users\ww\PDBminer-main\PDBminer", line 1255, in align
    alignment_info = align_uniprot_pdb(combined_structure.structure_id[i],
  File "c:\Users\ww\PDBminer-main\PDBminer", line 976, in align_uniprot_pdb
    df_align, mutations_in_all, warnings = processing_normal_alignment(uniprot_sequence,
  File "c:\Users\ww\PDBminer-main\PDBminer", line 890, in processing_normal_alignment
    df_align = get_aligned_df(uniprot_aligned, modified_pdb_aligned, pdb_aligned, uniprot_numbering_copy, b_factors)
  File "c:\Users\ww\PDBminer-main\PDBminer", line 850, in get_aligned_df
    df_align = pd.DataFrame(data={"uniprot_seq": uniprot_al,
  File "c:\CADD\anaconda3\envs\fragbase\lib\site-packages\pandas\core\frame.py", line 664, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "c:\CADD\anaconda3\envs\fragbase\lib\site-packages\pandas\core\internals\construction.py", line 493, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "c:\CADD\anaconda3\envs\fragbase\lib\site-packages\pandas\core\internals\construction.py", line 118, in arrays_to_mgr
    index = _extract_index(arrays)
  File "c:\CADD\anaconda3\envs\fragbase\lib\site-packages\pandas\core\internals\construction.py", line 666, in _extract_index
    raise ValueError("All arrays must be of the same length")
ValueError: All arrays must be of the same length
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "PDBminer", line 1713, in <module>
    run_list(input_file, args.cores, args.format, args.peptide_length)
  File "PDBminer", line 1652, in run_list
    pool.starmap(process_uniprot, [(uniprot_id, df, output_format, peptide_min_length) for uniprot_id in uniprot_list])
  File "c:\CADD\anaconda3\envs\fragbase\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "c:\CADD\anaconda3\envs\fragbase\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
ValueError: All arrays must be of the same length
```

could yo please give some suggetions how to fix it up?
many thanks,

Best,
Sh-Y

**Comment by pineappleK** [comment]
@MachineGUN001, hi. Perhaps you used Pandas 2.0 and above in your environment. I think you should back to pandas=1.2.4 as the authors claimed.

Here are some explanations. In Pandas 2.0 and above, the behavior regarding the construction of DataFrames from sequences of different lengths has changed, enforcing the requirement that all input sequences must be of the same length. In your situation, if the uniprot_al, uniprot_num, mod_al, and b_factor are not the same length, then constructing the DataFrame directly won't work.
```python
# Create an aligned dataframe for the chain.
df_align = pd.DataFrame(data={"uniprot_seq": uniprot_al,
                              "uniprot_pos": uniprot_num,
                              "pdb_seq": mod_al,
                              "b_factor": b_factor}) 
```

**Comment by MachineGUN001** [comment]
> ValueError: All arrays must be of the same length

thanks for your suggetions so much. however, after downgrading to pandas 1.24 as you mentioned, the error still occur.

`ValueError: All arrays must be of the same length`

Is there anything else that might be causing this error to occur?
many thanks

Sh-Y

**Comment by pineappleK** [comment]
Try to create a new environment and install all the packages like:

'''python
python3 -m pip --default-timeout=1000 install -r requirements.txt
'''
good luck~

**Comment by DegnKristine** [comment]
Hi @MachineGUN001, thank you for trying out PDBminer. 

I can re-create your problem if I disregard the dependency specifications of the tool. 

To solve this, I would recommend you to create a separate environment for the tool to avoid conflicts between different versions of dependencies required for each tool you might be using. 

If for some reason you do not want to do that, you can alternatively try to inspect your dependencies either using condas or pip depending on your environment:
```
conda activate env_name
conda list
```
since you are using a windows, something along the lines of: 
```
path\to\your\virtualenv\Scripts\activate 
pip list
```
Here you can inspect the versions of python, numpy, pandas, requests, biopython, matplotlib, networkx, seaborn and pyyaml. 

We tested PDBminer on Windows 11 with a conda enviroment, where it was successfully installed.

**Comment by MachineGUN001** [comment]
hi, @DegnKristine @pineappleK 
thanks for you kind helps. according to your suggestions, I re-installed create a separate environment, and pip requirement.txt. so far that works well. Looks like the problem is solved, although it's not clear that it was caused by that version inconsistency.

for my another question，the commandline as an example `!python PDBminer -g SSTR3 -u P05543 -m "T11S;C191S;R330L" -n 1 -f csv`

What is the approximate running time to complete this script, I have an Intel I5 processor.？

Many Many Thanks,

Best,
Sh-Y

**Comment by DegnKristine** [comment]
Great that you made it work! 

When I try to run your command it takes me 52 seconds :) (Apple M1 Chip, which might be a slightly faster performance, see https://recoverit.wondershare.com/mac-tips/apple-m1-chip-vs-intel-i5.html)

**Comment by MachineGUN001** [comment]
thanks for you kind help.
