### ISSUE TITLE
Adding a function to automatically download the .pdb file

### ISSUE THREAD

**Issue by realalanc** [ELELAB/PDBminer#72]
Adding such a function can help reducing the hardship building personal protein structure database
Anyone calls a dib?
If none, I may add this function after the Chinese new year holiday.

**Comment by DegnKristine** [comment]
Hello! 

Thank you for the comment, PDBminer actually does download the files (.cif format to overcome some of the pdb format challenges) and the removes them again to avoid take up space. I can see, if I can add the option to  make that choice based on user input. That would be a simple implementation. 

It might make sense to renumber the PDBs we are retaining since PDBminer already does the task, yet i can see that this could be a challenge with fusion products. 

What do you think could be useful for you?

Best, Kristine

**Comment by realalanc** [comment]
Greetings!
Thanks for your work and for sharing it!
Actually, I summit this idea when I am researching for a protein structure database with certain feature for Deep Learning.
I got a list of Uniprot ids, and I need to get the nearest available structure data, so I turned to your tool for help but failed due to the issue I submitted.
I consider it as a very common need when building dataset with structure.
If possible, we can develop a ‘experimental’ function to directly get the structure data, asking for bug reports and PRs, also, I am willing to offer my all possible strength to help after the vacation.
When talking about fusion products, if possible, may you tell me the exactly possible difficulty, so I may offer help? (Sorry, but I do not recognize where the problem is)
(By the way, I reported a bug in the Pull Request area, and if any mistake is taken by me, feel free to correct it) 
Thanks again for your open source spirit, and for your kindly concern about my idea. 
Apologies for not writing very properly due to my limited English level.
With my Best Wishes
Alan C. 

从 Windows 版邮件发送

发件人: Kristine Degn
发送时间: 2024年1月31日 23:03
收件人: ELELAB/PDBminer
抄送: Alan C; Author
主题: Re: [ELELAB/PDBminer] Adding a function to automatically download the.pdb file (Issue #72)

Hello!
Thank you for the comment, PDBminer actually does download the files (.cif format to overcome some of the pdb format challenges) and the removes them again to avoid take up space. I can see, if I can add the option to make that choice based on user input. That would be a simple implementation.
It might make sense to renumber the PDBs we are retaining since PDBminer already does the task, yet i can see that this could be a challenge with fusion products.
What do you think could be useful for you?
Best, Kristine
